# Start from a standard Python base image.
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

RUN pip install flask chromadb sentence-transformers ollama gunicorn

# This ensures the model is available instantly when the container starts.
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"


COPY . .

# Expose the port the API will run on
EXPOSE 5001

CMD ["python", "-m", "gunicorn", "--bind", "0.0.0.0:5001","--reload", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "--timeout", "180","src.api:app"]